"use client";

import { useState, useRef } from "react";
import Image from "next/image";

import {
	ToggleCard,
	Authenticator,
	SMSAuthenticator,
	PopUpTopBar,
	SecurityQuestionAuth,
} from "../../../components/security";

import { PiCaretUpBold, PiCaretDownBold } from "react-icons/pi";
import picIcon from "../../../../assets/images/icons/picIcon.svg";

export default function Security() {
	const [authAppToggled, setAuthAppToggled] = useState(false);
	const [smsAuthToggled, setSmsAuthToggled] = useState(false);
	const [securityQuestionToggled, setSecurityQuestionToggled] = useState(false);

	const [showAuthApp, setShowAuthApp] = useState(false);
	const [showSMSAuth, setShowSMSAuth] = useState(false);
	const [showSecurityQuestion, setShowSecurityQuestion] = useState(false);

	const saveAuth = () => {
		setShowAuthApp(false);
		setAuthAppToggled(true);
	};

	const saveSMSAuth = () => {
		setShowSMSAuth(false);
		setSmsAuthToggled(true);
	};

	const setSecurityQuestion = () => {
		setShowSecurityQuestion(false);
		setSecurityQuestionToggled(true);
	};
	return (
		<main className=" space-y-8 lg:space-y-8 text-[--text-secondary] border border-[--lines] p-5 h-full min-h-[80vh] rounded-2xl">
			<div className="pb-3 space-y-2">
				<h3 className="text-3xl text-[--color-brand] font-semibold">
					Security
				</h3>
				<p>
					You can reach us via our phone numbers, social media profiles, email
					etc.
				</p>
			</div>

			<div className="space-y-7">
				<ToggleCard
					heading="Authenticator app code"
					text="Enter a code generated by your authenticator app to confirm it’s you."
					recommended="yes"
					active={authAppToggled}
					toggleFunc={() => {
						authAppToggled === true
							? setAuthAppToggled(false)
							: setShowAuthApp(true);
					}}
				/>
				<ToggleCard
					heading="Text Message"
					text="Receive a six digit code by text message to confirm it’s you."
					recommended="no"
					active={smsAuthToggled}
					toggleFunc={() =>
						smsAuthToggled === true
							? setSmsAuthToggled(false)
							: setShowSMSAuth(true)
					}
				/>
				<ToggleCard
					heading="Security Question"
					text="Answer a security question to confirm it’s you."
					recommended="yes"
					active={securityQuestionToggled}
					toggleFunc={() =>
						securityQuestionToggled === true
							? setSecurityQuestionToggled(false)
							: setShowSecurityQuestion(true)
					}
				/>
			</div>

			{showAuthApp && (
				<div className="fixed top-[-40px] right-0 w-full md:w-[450px] h-[105vh] pb-[5vh] bg-white overflow-y-auto shadow">
					<div className="fixed top-0 right-0 z-[10] w-full md:w-[450px] bg-transparent pr-1">
						<PopUpTopBar
							close={() => setShowAuthApp(false)}
							title="About Investment"
							desc="Use the form below to purchase enough investment units."
						/>
					</div>
					<div className="pt-[230px]">
						<Authenticator
							saveFunc={() => saveAuth()}
							closeFunc={() => setShowAuthApp(false)}
						/>
					</div>
				</div>
			)}

			{showSMSAuth && (
				<div className="fixed top-[-40px] right-0 w-full md:w-[450px] h-[105vh] pb-[5vh] bg-white overflow-y-auto shadow">
					<div className="fixed top-0 right-0 z-[10] w-full md:w-[450px] bg-transparent pr-1">
						<PopUpTopBar
							close={() => setShowSMSAuth(false)}
							title="Text Message"
							desc="Receive a prompt from your mobile app to confirm it’s you."
						/>
					</div>
					<div className="pt-[230px]">
						<SMSAuthenticator
							saveFunc={() => saveSMSAuth()}
							closeFunc={() => setShowSMSAuth(false)}
						/>
					</div>
				</div>
			)}

			{showSecurityQuestion && (
				<div className="fixed top-[-40px] right-0 w-full md:w-[450px] h-[105vh] pb-[5vh] bg-white overflow-y-auto shadow">
					<div className="fixed top-0 right-0 z-[10] w-full md:w-[450px] bg-transparent pr-1">
						<PopUpTopBar
							close={() => setShowSecurityQuestion(false)}
							title="Security Question"
							desc="Answer a security question to confirm it’s you."
						/>
					</div>
					<div className="pt-[230px] h-full">
						<SecurityQuestionAuth
							saveFunc={() => setSecurityQuestion()}
							closeFunc={() => setShowSecurityQuestion(false)}
						/>
					</div>
				</div>
			)}
		</main>
	);
}
