import React from "react";

import Image from "next/image";
import hash from "../../../assets/images/barcode.png";
import { IoCopySharp } from "react-icons/io5";

const Authenticator = ({ saveFunc, closeFunc }) => {
	return (
		<div className="px-8 py-5 flex flex-col gap-5 items-center text-[--primary]">
			<div className="w-[220px] h-[220px]">
				<Image
					src={hash}
					alt="hash"
					width="auto"
					height="auto"
					className="w-full h-full"
				/>
			</div>
			<h3 className="text-xl font-medium text-center">
				Scan this QR Code or Setup Manually
			</h3>
			<p>
				Complete set-up by scanning the QR Code shown. If you can’t scan the
				code, coply the key shown below.
			</p>
			<p className="font-medium text-lg">
				NE5L 4ABV VNXH 266P{" "}
				<IoCopySharp className="text-[--text-secondary] inline-block ml-3" />
			</p>
			<input
				type="text"
				placeholder="Enter code generated by your authenticator app"
				className="form-input"
			/>
			<div className="space-y-3 w-full pt-8 pb-3">
				<button
					className="block w-full py-3 px-5 rounded text-white bg-[--color-brand] border border-[--color-brand]"
					onClick={() => saveFunc()}
				>
					Save
				</button>
				<button
					className="block w-full py-3 px-5 rounded text-[--color-brand] border border-[--color-brand]"
					onClick={() => closeFunc()}
				>
					Close
				</button>
			</div>
		</div>
	);
};

export default Authenticator;
