const queryKeys = {
  signUp: "signUp",
  confirmEmailOtp: "confirmEmailOtp",
  requestEmailOtp: "requestEmailOtp",
  signIn: "signIn",
  getSession: "getSession",
  signOut: "signOut",
  kycIDPicture: "kycIDPicture",
  kycPicture: "kycPicture",
  changePassword: "changePassword",
  resetPassword: "resetPassword",
  confirmResetPassword: "confirmResetPassword",
  addKycInfo: "addKycInfo",
  setSecurityQuestions: "setSecurityQuestions",
  getNotificationPreferences: "getNotificationPreferences",
  setNotificationPreferences: "setNotificationPreferences",
  setNextOfKin: "setNextOfKin",
  getNextOfKin: "getNextOfKin",
  initiateTopUp: "initiateTopUp",
  getWallet: "getWallet",
  getSupportedBanks: "getSupportedBanks",
  resolveBankAccount: "resolveBankAccount",
  addBankAccount: "addBankAccount",
  getBankAccounts: "getBankAccounts",
  deleteBankAccount: "deleteBankAccount",
};

export default queryKeys;
